apiVersion: apps/v1
metadata:
    name: basic-flask-app-deployment
    labels: 
        app: demo-deployment
kind: Deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: flask
    template:
        metadata:
            labels:
                app: flask
        spec:
            containers:
                - name: flask-k8s-demo
                  image: jdial1996/basic-flask-app:v1
                  ports:
                    - containerPort: 5000
                  imagePullPolicy: IfNotPresent 
                  livenessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 30
                    periodSeconds: 30
                    # Liveness probe: if http request fails pod is deemed unhealthy
                  readinessProbe:  
                #    check port 5000 every 3 seconds after an initial delay of 15 seconds
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 15
                    periodSeconds: 3
                    # once the readiness probe succeeds kubernetes will know that the pod is ready for business (will then go to the liveness probe)

---

apiVersion: v1
kind: Service
metadata: 
    name: basic-flask-app-service
spec:
    selector:
        app: flask
    type: LoadBalancer
    ports:
        - protocol: "TCP"
          port: 6000
          targetPort: 5000
